# These are supported funding model platforms
github: OE-LUCIFER
# patreon: [username]
# open_collective: [username]
# ko_fi: [username]
# tidelift: [platform-name/package-name]
# community_bridge: [project-name]
# liberapay: [username]
# issuehunt: [username]
# lfx_crowdfunding: [project-name]
# polar: [username]
buy_me_a_coffee: oevortex
# custom: ['link1', 'link2']
